### ISSUE TITLE
References are broken

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/webarch#1]
Many of the references are not in Respec's bibliography. Including:
- CHIPS
- CUAP
- EXTLANG
- Eng90
- IANASchemes
- OWL10
- QA
- RDDL
- RDFXML
- RFC2141
- RFC2326
- RFC2616
- RFC2717
- RFC2718
- RFC3261
- RFC3920
- VOICEXML2
- XLink
- XLink10
- XMLNS
- XMLSCHEMA

**Comment by ylafon** [comment]
RFC2616 is HTTP11 in respec, RFC2141 is URN
VOICEXML2... 2.0 or 2.1 ?
XLink10 is XLINK10
XMLSCHEMA is XMLSCHEMA-[012]
I'll add the others in respec.

**Comment by htInEdin** [comment]
Yves Lafon writes:

> RFC2616 is HTTP11 in respec, RFC2141 is URN
> VOICEXML2... 2.0 or 2.1 ?
> XLink10 is XLINK10
> XMLSCHEMA is XMLSCHEMA-[012]

I'll make those edits as part of my learning curve wrt the toolchain

> I'll add the others in respec.

Thanks,

**Comment by plinss** [comment]
Closing old issues

**Comment by torgo** [comment]
We discussed this and decided that since this document has not been worked on and has never been put forward as an update to WebArch we will not put effort on fixing these or other issues on webarch at this time.
