### ISSUE TITLE
Diff view 

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/webarch#5]
@htInEdin, I'm wondering if instead of manually marking up changes with del and ins, we  just provide a link to http://services.w3.org/htmldiff ? it does exactly the same thing automagically and leaves the source document much more legible for people who just want to read the document. 

We would just need to pick an initial moment in time from which to base off and then just point to the latest editor's draft. It also avoid human error if not recording a change.  

WDYT?

**Comment by htInEdin** [comment]
My experience is that the auto-diffs are never as good as ones that
are created thoughtfully by the editor(s).  Also, it makes it much
easier to revert diffs if after feedback you change your mind.

It requires discipline, but it's worth it in my experience.

**Comment by marcoscaceres** [comment]
IMO, being able to view changes is really the point of the [commit history](https://github.com/w3ctag/webarch/commits/gh-pages). I don't know how many people actually care about seeing the changes (it's generally acknowledged that the awww is grossly outdated and doesn't match reality - so it should be ok to discard most of the content without worrying too much about the original stuff). 

I think there should be consensus about how the document should be edited from the TAG members. If we do keep the dels and ins, then we should at least provide some javascript to disable/enable viewing them (and have them off by default).

**Comment by torgo** [comment]
We discussed this and decided that since this document has not been worked on and has never been put forward as an update to WebArch we will not put effort on fixing these or other issues on webarch at this time.
