### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by mnot** [w3ctag/webarch#7]
Should the Web Architecture mention JSON? It's an extremely common format, and arguably it embodies principles that are important to WebArch.

The relationship to / tradeoffs between JSON and XML might also be interesting to explore.

See also: https://www.mnot.net/blog/2012/04/13/json_or_xml_just_decide

**Comment by cynthia** [comment]
We discussed this and decided that since this document has not been worked on and has never been put forward as an update to WebArch we will not put effort on fixing these or other issues on webarch at this time.
