### ISSUE TITLE
TLS and security

### ISSUE THREAD

**Issue by mnot** [w3ctag/webarch#9]
We need an architectural view on the properties that TLS provides and its end-to-end nature.

Likely needs to incorporate:
  * https://www.w3.org/2001/tag/doc/web-https
  * https://www.w3.org/2001/tag/doc/encryption-finding/

**Comment by cynthia** [comment]
We discussed this and decided that since this document has not been worked on and has never been put forward as an update to WebArch we will not put effort on fixing these or other issues on webarch at this time.
